name: Build and Deploy Java App to Azure App application

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: icarosregisry.azurecr.io
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t icarosregisry.azurecr.io/minha-app:${{ github.sha }}

      - name: Push Docker Image
        run: docker push icarosregisry.azurecr.io/minha-app:${{ github.sha }}

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: icarosregisry.azurecr.io/minha-app:${{ github.sha }}