name: Build, Push and Deploy to Azure Web App (Publish Profile)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_NAME: icaros       # nome do Container Registry (lowercase)
  IMAGE_NAME: minha-app          # nome da imagem (sem espaços)
  WEBAPP_NAME: icaros     # nome do seu App Service

jobs:  
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1. Login no ACR (usando usuário/senha do ACR)
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 2. Build e push da imagem
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
      # 3. Deploy no Azure App Service (via publish profile)
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
